### ISSUE TITLE
Editing container params feature

### ISSUE THREAD

**Issue by ramzes642** [crosbymichael/not-dockers-ui#171]
Hello, is it possible to add editing feature like that in kitematic?
A lot of packages asking to edit env variables (ex. mysql), and it will be great to modify ports and volumes after creating container.
Sadly, but nowone except kitematic gui supports editing, even monster rancher can modify ports, but it doesn't work.
Dockerui is lightweight and great, so this feature is very important for me (I think for others too).
It is very complicated to do this in console with commiting images, restarting them.

**Comment by kevana** [comment]
From the [docs](https://docs.docker.com/kitematic/userguide/#adding-environment-variables):

> When you “Save” the changed environment variables, the container will be stopped, removed and re-created.

I don't think it's possible to modify ports and volumes of a running container without destroying it and creating a new one, Kitematic just does these steps for you. I don't have much of a use for this but if anyone wants to give it a shot I'll gladly merge it.

**Comment by ramzes642** [comment]
Hi, I tried to implement this feature. I am new to angular and docker api, please look at my commit:
https://github.com/ramzes642/dockerui/commit/ad0d23d6868218e3b0ec19eb92fca86629d5298b

I've made one change, I don't know if it correct - changed parameter "repo" to "tag" in commit method, otherwise it was failing if repo has semicolon in name.

**Comment by kevana** [comment]
Thanks, I'll try to review it soon

**Comment by ramzes642** [comment]
Now with ports editing and filesystem binds. https://github.com/ramzes642/dockerui/commit/50d33a07dfea390260d63d6627eb542cdc23bb9c
If you like it, I can make a pull request, 
![2016-02-24 3 23 08](https://cloud.githubusercontent.com/assets/2124209/13271421/fe845ed4-daa5-11e5-8244-4d07b91b1240.png)
![2016-02-24 3 24 14](https://cloud.githubusercontent.com/assets/2124209/13271453/20365bea-daa6-11e5-9fbb-ae19a37ac68c.png)
![2016-02-24 3 21 47](https://cloud.githubusercontent.com/assets/2124209/13271507/6f031ed4-daa6-11e5-8ff1-b5ac57f2abcd.png)
![2016-02-24 3 21 53](https://cloud.githubusercontent.com/assets/2124209/13271508/6f200288-daa6-11e5-889d-a87dcd1712e7.png)

**Comment by kevana** [comment]
A PR would be great

**Comment by kevana** [comment]
Implemented in #184, thanks!
